service: cart-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: 'dev'
  region: 'us-west-1'

plugins:
    - serverless-offline

functions:
  main:
    handler: dist/main.handler
    runtime: nodejs18.x
    events:
      - http:
          path: /
          method: ANY
          cors: false
          private: false
      - http:
          path: '{proxy+}'
          method: ANY
          cors: false
          private: false
    
      

    
